library(dplyr)
library(tidyverse)
library(shiny)
library(shinydashboard)
library(ggplot2)
library(DT)
library(dplyr)
library(tidyverse)
library(roxygen2)

conso_commune <- read.csv('data/consommation-electrique-par-secteur-dactivite-commune-propre.csv', sep=",", encoding = "UTF-8")
conso_departement <- read.csv('data/consommation-electrique-par-secteur-dactivite-departement-propre.csv', sep=",", encoding = "UTF-8")
conso_region <- read.csv('data/consommation-electrique-par-secteur-dactivite-region-propre.csv', sep=",", encoding = "UTF-8")
prod_commune <- read.csv('data/production-electrique-par-filiere-a-la-maille-commune-propre.csv', sep=",", encoding = "UTF-8")
prod_departement <- read.csv('data/production-electrique-par-filiere-a-la-maille-departement-propre.csv', sep=",", encoding = "UTF-8")
prod_region <- read.csv('data/production-electrique-par-filiere-a-la-maille-region-propre.csv', sep=",", encoding = "UTF-8")

vect_annee <- unique(prod_region$annee)
vect_region <- unique(conso_region$nom_region)
vect_departements <- unique(conso_departement$nom_departement)
vect_commune <- unique(conso_commune$nom_commune)

shinyApp(ui = ui, server = server)
